### PR TITLE
Alias Description Helpers - Alias Template, FontAwesome

### PR DESCRIPTION
**Pull request by geelongmicrosoldering**
# Description
**This is an expansion of another [PR](https://github.com/pagermon/pagermon/pull/512) which will now be closed**

Note sure if anyone noticed but the link in the helpBlock span is dead (FontAwesome changed URL Structure).
I never really liked navigating to another website/tab to select an icon anyway, so I wrote a Helper Modal/Function.

I've also added an Alias Template function after reading a suggestion from [this issue](https://github.com/pagermon/pagermon/issues/504)

**The Helpers appear as buttons next to the appropriate inputs:**
pm_alias_helpers

**Alias Templates can be defined in Settings:**
pm_alias_template_settings

**To use an Alias Template, find it in the list:**
pm_alias_template_details
You can also use filter if your list becomes large. Click the Template you wish to use, and the appropriate Agency, Icon, Color, and Ignore state will be set. All you need to do is give your alias a name.

**To select from one of the available FontAwesome icons, click "PICK":**
pm_alias_fontawesome_details

**You can also filter the icons to narrow your search. Hovering over an icon will show you the icons name, both as a title, and in the footer of the modal:**
pm_alias_fontawesome_details_filtered_hover
Click the icon you wish to use, and it will be inserted into the icon field.

Fixes # (FontAwesome Link changed, and may change again in future)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] This change MAY require a documentation update, although its pretty self explanatory

# How Has This Been Tested?

- [x] Tested on my own server, encourage someone else to test

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by eopo** [comment]
Thanks for your work, but common practice is to keep separate features in separate branches, so that all changes regarding to this can be reviewed and handled separately.

Looks nice though!

**Comment by eopo** [comment]
Closes #512 
Closes #504

**Comment by geelongmicrosoldering** [comment]
> Thanks for your work, but common practice is to keep separate features in separate branches, so that all changes regarding to this can be reviewed and handled separately.
> 
> Looks nice though!

I considered it, and hesitated for a moment, but the 2 were so similar in how they are written (I mostly copied and pasted my own code).
I ended up making the former FontAwesome helper slightly better anyway (search/filter for quickly finding icon).

**Comment by marshyonline** [comment]
This is looking good - will do some testing and sanity checking today

**Comment by geelongmicrosoldering** [comment]
> I'll try and give this a test later in the week, looking good tho, as per the others, needs a changelog entry.

done :)

**Comment by DanrwAU** [comment]
Does this need Unit Tests written?

**Comment by geelongmicrosoldering** [comment]
> Does this need Unit Tests written?

I am yet to learn how the tests are written, but im not sure what you would test. Im outside the loop on testing.

The flow of adding an alias doesnt change from before. But there is the ability to add alias templates which get stored in config. So i guess I could write something to confirm adding alias templates works.

Is there something like that currently for text matching/api key? Pretty much works the same way.

If i get a chance ill took into it.

**Comment by marshyonline** [comment]
> Does this need Unit Tests written?

Def's needs the tests

**Review by marshyonline — APPROVED** [review]

**Pull request merged**
