### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by ionenwisseling**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated changelog.md with changes made

### CODE REVIEW

**Comment by eopo** [comment]
Please tell us, how your change would improve the project

**Comment by ionenwisseling** [comment]
I want pocsag meldingen

**Review by marshyonline — CHANGES_REQUESTED** [review]
These changes do not belong in this file.

**Comment by marshyonline** [comment]
Please open a new PR, Following the PR Template with real changes.
The changes in the PR are not valid

**Pull request closed without merging**
