### PR TITLE
Support for US/CA SAME EAS Messages - Purely Client side

### PR DESCRIPTION
**Pull request by MaxwellDPS**
# Support for US/CA SAME EAS Messages 
# Description

I have added native support for EAS messages via multimon-ng. It runs 100% on the client side and requires no server side code changes. _**Its gonna need a little TLC, Ill fix it up tomorrow.**_ But it introduces SAME decoding via the dsame.js import in the reader.js 

It listens for the line `EAS:  ZCZC-ORG-EEE-PSSCCC-PSSCCC+TTTT-JJJHHMM-LLLLLLLL     -` from multimon and decodes according to [SAME spec](https://en.wikipedia.org/wiki/Specific_Area_Message_Encoding)

Javascript was adapted from [DSAME](https://github.com/cuppa-joe/dsame), and has some new EEE codes added: SQW, BLU

only external library is moment.js so no new packages will be needed for the client.

Addresses are the following schema `LLLL-ORG` so for the exaple below the address is `KOAX-WXR`
> ZCZC-WXR-TOR-031109+0015-3650000-KOAX/NWS    -

If the message were as follows the address would be `KUCV-EAS`
> ZCZC-EAS-RWT-031109+0015-3650000-KUCV/FM    -

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] [https://wx.maxwelldps.com/](https://wx.maxwelldps.com/)
- [  ] More tests to come

# Checklist:

I will do these tomorrow

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have updated changelog.md with changes made

### CODE REVIEW

**Comment by davidmckenzie** [comment]
This is pretty neat, nice one! I'd suggest popping that huge wall of variables out into a separate constants file for readability and to make future updates easier... though you might want to consider turning that whole decoding part into an NPM library that can be reused elsewhere, it looks pretty useful

**Comment by MaxwellDPS** [comment]
@davidmckenzie I sure do appericate it! I have updated the files and split the vars into dsame-vars.js. I did clean up the reader.js and updated the reader.sh to notate protocols that can be used in the comments. I have updated the changelog as well. I will work on making this an npm package, haven't ever done that so, if you have any resources it would be much appericated! 

Once it is an npm package I will refork and update using that way, Dont have a time line on that tho.

Also very much so a noob at JS, if there are any improvements or anything you would like me to add please do let me know!

**Comment by MaxwellDPS** [comment]
Ok, Added a few commits lol but fixed a bug :)

```
multimon-ng 1.1.8
  (C) 1996/1997 by Tom Sailer HB9JNX/AE4WA
  (C) 2012-2019 by Elias Oenal
Available demodulators: POCSAG512 POCSAG1200 POCSAG2400 FLEX EAS UFSK1200 CLIPFSK FMSFSK AFSK1200 AFSK2400 AFSK2400_2 AFSK2400_3 HAPN4800 FSK9600 DTMF ZVEI1 ZVEI2 ZVEI3 DZVEI PZVEI EEA EIA CCIR MORSE_CW DUMPCSV X10 SCOPE
2020-07-23 10:39:03: Enabled demodulators: EAS
2020-07-23 10:39:03: EAS: NNNN
2020-07-23 10:39:04: EAS: NNNN
2020-07-23 10:39:05: EAS: NNNN
2020-07-23 10:39:14: WXYZ-CIV: The Civil Authorities  have issued a Shelter in Place Warning valid until 12:15 PM for the following counties in Nebraska: Lancaster. (WXYZ)
```

**Comment by MaxwellDPS** [comment]
Ok, I just removed dsame.js and dsame-vars.js and made the nodeJS package [jsame](https://www.npmjs.com/package/jsame). 
[jsame github](https://github.com/maxwelldps/jsame)

So I have added `"jsame": "^0.1.2"` to packages.json and the only edits to reader.js now are

```js
var SAME = require('jsame'); //Import jSAME EAS decode 
```

```js
else if (line.match(/EAS[:|]/)) {
     var decodedMeassage = SAME.decode(line); // Returns a list with [ Message, address ]
      // Addresses are the following schema LLLL-ORG so for the exaple following the address is "KOAX-WXR" :  ZCZC-WXR-TOR-031109+0015-3650000-KOAX/NWS -
      if (decodedMeassage) {
          address = decodedMeassage["LLLL-ORG"]
          message = decodedMeassage["MESSAGE"]
          trimMessage = decodedMeassage["MESSAGE"]
          datetime = moment().unix(); //just get current time
      } else {
          address = '';
          message = false;
          trimMessage = '';
      }
```

Just tested it looks good
```
max@cdn:~/test$ git clone git@github.com:MaxwellDPS/pagermon.git
Cloning into 'pagermon'...
remote: Enumerating objects: 320, done.
remote: Counting objects: 100% (320/320), done.
remote: Compressing objects: 100% (217/217), done.
remote: Total 5916 (delta 191), reused 194 (delta 94), pack-reused 5596
Receiving objects: 100% (5916/5916), 4.45 MiB | 16.50 MiB/s, done.
Resolving deltas: 100% (3775/3775), done.
max@cdn:~/test$ cd pagermon/client/
max@cdn:~/test/pagermon/client$ npm install
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN pagermon-client@0.0.0 No repository field.

added 78 packages from 113 contributors and audited 78 packages in 2.711s

2 packages are looking for funding
  run `npm fund` for details

found 1 high severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
max@cdn:~/test/pagermon/client$ echo "EAS:  ZCZC-WXR-RWT-055027-055039-055047-055117-055131-055137-055139-055015-055071+0030-0771800-KMKX/NWS     -" | node reader.js
created config file - set your api key in ./config/config.json
max@cdn:~/test/pagermon/client$ echo "EAS:  ZCZC-WXR-RWT-055027-055039-055047-055117-055131-055137-055139-055015-055071+0030-0771800-KMKX/NWS     -" | node reader.js
{ MESSAGE:
   'The National Weather Service in Milwaukee, WI has issued a Required Weekly Test valid until 1:30 PM for the following counties in Wisconsin: Calumet, Dodge, Fond du Lac, Green Lake, Manitowoc, Sheboygan, Washington, Waushara, Winnebago. (KMKX/NWS)',
  ORG: 'WXR',
  EEE: 'RWT',
  PSSCCC_LIST:
   [ '055015',
     '055027',
     '055039',
     '055047',
     '055071',
     '055117',
     '055131',
     '055137',
     '055139' ],
  TTTT: '0030',
  JJJHHMM: '0771800',
  STATION: 'KMKX',
  LLLLLLLL: 'KMKX/NWS',
  COUNTRY: 'US',
  'LLLL-ORG': 'KMKX-WXR' }
2020-07-23 22:03:43: KMKX-WXR: The National Weather Service in Milwaukee, WI has issued a Required Weekly Test valid until 1:30 PM for the following counties in Wisconsin: Calumet, Dodge, Fond du Lac, Green Lake, Manitowoc, Sheboygan, Washington, Waushara, Winnebago. (KMKX/NWS)
Input died!
```

**Comment by davidmckenzie** [comment]
Beautiful 👍

**Pull request merged**
