### PR TITLE
Better Regex/Text Matching

### PR DESCRIPTION
**Pull request by geelongmicrosoldering**
# Description

I wanted to be able to not just label/highlight certain regex matches, but actually replace them with reasonably complex replacements based on matched regex groups.
For example, matching a known address format and linking it to Google Maps, replacing abbreviations for words, codes with descriptions, urls with links, words with images (why not).

Really, you should be able to make your own highlights/labels (including bootstrap labels), and have custom highlighted text/links/whatever, based on a regex match.
Some examples of replacements:
**Match STRUCTURE FIRE, but not NON STRUCTURE FIRE, Replace with Danger Bootstrap Label**
Match `((?<!NON)[\s]STRUCTURE\sFIRE[\s])`
Replacement `<a href="?q=STRUCTURE%20FIRE" class="label label-danger">$1</a>`
**Match NON STRUCTURE FIRE & NON-STRUCTURE FIRE, Replace with Warning Bootstrap Label**
Match `([\s]NON[\s-]STRUCTURE\sFIRE[\s])`
Replacement `<a href="?q=NON%20STRUCTURE%20FIRE" class="label label-warning">$1</a>`

I initially did this a different way, but decided it should really be part of the existing Text Matching, and (I think) can be without breaking anything.

This PR has the following changes:
- Replace "Highlight" checkbox with a dropdown, giving you the option to Label, Highlight, or Replace on a per filter basis
- Allow for regex replacements that include matched groups ($1, $2, $3 etc)
- Drag and Drop to reorder filters to better suit your needs (because when you have a lot of them, its easy to create conflicts due to the order they are processed)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Tested on live production server, but would encourage others to test and scrutinize before merge 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas (I have not, but i'm not sure this is needed for this)
- [ ] I have updated changelog.md with changes made (still unsure how to do this, will let someone else)

### CODE REVIEW

**Comment by marshyonline** [comment]
Nice, i will look over this in the coming days.
If this now includes Regex Replace, the plugin for this could be removed.

**Comment by geelongmicrosoldering** [comment]
> Nice, i will look over this in the coming days. If this now includes Regex Replace, the plugin for this could be removed.

I've actually never used RegexReplace Plugin, because there's only the one replacement there.

But i assume based on this 
> Option to allow matching and replacing against incoming messages

It effects incoming messages and stores them in the database after replacement? If so, this doesn't do that. The replacements happen user side only. I kindof prefer that, because the raw messages data isn't effected by my erroneous regexing lol

**Comment by geelongmicrosoldering** [comment]
@marshyonline not that I'm on there often, but is the discord group for pagermon active? anyone able to send me an invite if so? microsoldering@gmail.com

**Comment by marshyonline** [comment]
> @marshyonline not that I'm on there often, but is the discord group for pagermon active? anyone able to send me an invite if so? [microsoldering@gmail.com](mailto:microsoldering@gmail.com)

Yeah it's still active, you can join here: https://discord.gg/vdfgSejA

**Comment by geelongmicrosoldering** [comment]
> > @marshyonline not that I'm on there often, but is the discord group for pagermon active? anyone able to send me an invite if so? [microsoldering@gmail.com](mailto:microsoldering@gmail.com)
> 
> Yeah it's still active, you can join here: https://discord.gg/vdfgSejA

Much obliged

**Comment by DanrwAU** [comment]
I'll try and do some reviews this week. One note tho, this should be rebased to develop ;)

**Comment by geelongmicrosoldering** [comment]
> I'll try and do some reviews this week. One note tho, this should be rebased to develop ;)

i dont know how :joy:

**Comment by ArrEssJay** [comment]
In the meantime, a super hacky but flexible workaround is simply to pipe the output of multimon-ng through `sed` en-route to pagermon:

For example, replacing priority codes with something more human readable:
```
multimon-ng -q -b1 -c -a POCSAG512 -a POCSAG1200 -a POCSAG2400 -f alpha -t raw /dev/stdin |\
+ sed 's/Alpha:   @@/Alpha:   !!! /' - |\
+ sed 's/Alpha:   QD/Alpha:   !!  /' - |\
+ sed 's/Alpha:   Hb/Alpha:   !   /' - |\
node reader.js
```

**Comment by geelongmicrosoldering** [comment]
> In the meantime, a super hacky but flexible workaround is simply to pipe the output of multimon-ng through `sed` en-route to pagermon:
> 
> For example, replacing priority codes with something more human readable:
> 
> ```
> multimon-ng -q -b1 -c -a POCSAG512 -a POCSAG1200 -a POCSAG2400 -f alpha -t raw /dev/stdin |\
> + sed 's/Alpha:   @@/Alpha:   !!! /' - |\
> + sed 's/Alpha:   QD/Alpha:   !!  /' - |\
> + sed 's/Alpha:   Hb/Alpha:   !   /' - |\
> node reader.js
> ```

That works for permanently replacing text with text before input to the database.

Unfortunately it wont work for dynamic changes that can easily be reverted/corrected (if a mistake was made) and wont let you, for example, replace match sets with pretty bootstrap elements.

**Comment by marshyonline** [comment]
@geelongmicrosoldering Can we fix the merge conflicts so we can push this one?

**Comment by geelongmicrosoldering** [comment]
> @geelongmicrosoldering Can we fix the merge conflicts so we can push this one?

i thought i did but it broke and i cant tell where

**Pull request merged**
