### PR TITLE
Remove double quote stripping 

### LINKED ISSUE #180: Double quote character is stripped from messages
Double quote character `"` is stripped if contained in the message.
This happened when message is stored in database.

Note: If this character is added manually in the database, it is displayed correctly.

### PR DESCRIPTION
**Pull request by DanrwAU**
# Description

Removes the section of API.js that strips double quotes from messages - Knex protects against SQLInjection so this is no longer required

Fixes #180 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Submitted messages containing SQL Statements and confirmed these were NOT executed

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have updated changelog.md with changes made

### CODE REVIEW

**Comment by davidmckenzie** [comment]
I have a vague recollection that was there to protect against something else. Either the regex text swap/highlighting thing, or the old search functions... if it tests ok from your side then it's probably all good though :)

**Comment by DanrwAU** [comment]
Hmmmm i might run it through a full set of tests. I only really tested SQL Injection. 😁

**Comment by DanrwAU** [comment]
Searching and the highlighter seem to work ok for my use case. 

I'll leave it run overnight and checck for any issues 😃

**Comment by DanrwAU** [comment]
This seemed to run ok Overnight, nothing strange comparing to 0.3.0 build

**Pull request merged**
