### PR TITLE
FontAwesome Helper for Alias Details

### PR DESCRIPTION
**Pull request by geelongmicrosoldering**
Adds Helper Modal for easier selection of FontAwesome Icons

# Description

Note sure if anyone noticed but the link in the helpBlock span is dead (FontAwesome changed URL Structure).
I never really liked navigating to another website/tab to select an icon anyway, so I wrote a Helper Modal/Function.

Click "PICK", scroll through all the available icons, click on one.
faHelper1
faHelper2

Fixes # (FontAwesome Link changed, and may change again in future)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [x] I did the tests, it does the things

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by eopo** [comment]
This looks really cool, thanks a lot!
I'll have a closer look at it later.

**Comment by geelongmicrosoldering** [comment]
Think i royally fkd the base branch selection when i submitted this PR and dont know if i can fix it now without redoing it. You can tell i don't hubgit often.

Any suggestions for what i should do there? I've done it on another PR too

**Comment by eopo** [comment]
We can rebase it, that is not too big of a problem.

**Comment by geelongmicrosoldering** [comment]
> We can rebase it, that is not too big of a problem.

sweet! i thought i could just switch the base by editing it from here but then i think the issue is that the rest of the code base is behind develop. it didnt look right so i switched it back

**Comment by geelongmicrosoldering** [comment]
Closing this PR due to expanding on it and making it part of [another](https://github.com/pagermon/pagermon/pull/514), better PR

**Pull request closed without merging**
