### PR TITLE
DoS Vulnerability Fix

### PR DESCRIPTION
**Pull request by DanrwAU**
# Description

Another DoS Vulnerability as a result of #278 

Fixes # No open issue

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Confirmed Changes no longer loop

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have updated changelog.md with changes made

### CODE REVIEW

**Comment by s3m1s0n1c** [comment]
:( bad news..
This isn't all fixed..

The Following Characters have issues on v0.3.1 in search query
@ $ ; ,

**Comment by davidmckenzie** [comment]
Well, shit... it's gonna be unencoding things when calling `window.location.search`

**Comment by davidmckenzie** [comment]
Got an idea to try tomorrow - urlencode `window.location.search` as well (except for the first `?`) and compare that to qString... that _should_ do it

**Comment by davidmckenzie** [comment]
The behavior of `window.location.search` seems really inconsistent... give it a go in browser console, experiment on any random page (like this one) with various query strings with special chars, it seems to convert some but not others. This might even vary from browser to browser.

**Comment by s3m1s0n1c** [comment]
Mmm interesting... I'm using Firefox.. Will try in other browsers/sites tomorrow

**Comment by marshyonline** [comment]
Confirmed this is an issue still in any browser

**Comment by davidmckenzie** [comment]
```
[pmon]  2019-05-15 08:39:39  error : SELECT messages.*, capcodes.alias, capcodes.agency, capcodes.icon, capcodes.color, capcodes.ignore, capcodes.id AS aliasMatch
      FROM messages_search_index
      LEFT JOIN messages ON messages.id = messages_search_index.rowid  LEFT JOIN capcodes ON capcodes.id = messages.alias_id  WHERE messages_search_index MATCH 'test2>?''"&,' ORDER BY messages.timestamp DESC; - SQLITE_ERROR: malformed MATCH expression: [test2>?'"&,]
^C::1 - - [14/May/2019:22:39:39 +0000] "GET /api/messageSearch?limit=&page=1&q=test2%3E%3F%27%22%26, HTTP/1.1" 500 120 "http://localhost:3000/?q=test2%3E%3F%27%22%26%2C" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
```

**Pull request merged**
