### PR TITLE
Plugin - MessageRepeat

### PR DESCRIPTION
**Pull request by marshyonline**
# Description

Allows the server to forward all incomming messages to another Pagermon Server / API

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Ran local test's and on my production servers.
Code also passed through eslint

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have updated changelog.md with changes made

### CODE REVIEW

**Comment by marshyonline** [comment]
Only issue I can see with this is when you point it at the same server it ends up in an infinite loop
Changing it's Scope to afterMessage would only send messages that have matched if running in PDW mode?

**Comment by davidmckenzie** [comment]
Could add an extra field in the message data. If that field exists and == some kind of unique identifier for the current box, then ignore. This could all be handled in the same plugin since the whole `req.body` object is passed through.

Plugin could generate a random UUID and store it in the pluginConf, then send that as `relayID` or something.

**Comment by marshyonline** [comment]
Ohhhh that's a good idea.
BeforeMessage can make the server ignore a message. 

I'll have a poke tomorow

**Comment by DanrwAU** [comment]
Did a quick install and test, looks good. 👍

**Comment by marshyonline** [comment]
Couldnt think of a nice way to auto set the UUID
so we force the user to user a UUID on config 
Servers will now no longer loop there own messages :D

**Pull request merged**
