### PR TITLE
Remove client

### PR DESCRIPTION
**Pull request by DanrwAU**
# Description

PR to remove the client from the main Repo

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Yes

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have updated changelog.md with changes made

### CODE REVIEW

**Comment by davidmckenzie** [comment]
Lets hold on this for 0.3.0, I remember someone mentioning a virtual dir reference thingo that links repos together. I wanna look at that again, see if we can make it neater :)

Plus... I forgot to put my changes to import.js in the other repo lol

**Comment by DanrwAU** [comment]
Ok ill delete this one for now :)

**Comment by DanrwAU** [comment]
Possibly submodules ?  

https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by davidmckenzie** [comment]
That sounds like it :) And this thing to retain commit history https://help.github.com/en/articles/splitting-a-subfolder-out-into-a-new-repository

**Comment by marshyonline** [comment]
Ahh yes 
Sounds good

**Pull request closed without merging**
