### PR TITLE
WIP Implemented column hide/show functionality and name change

### LINKED ISSUE #318: Set Column Header names
The functionality to set column header names and hide/show column headers separately 

EG Time/Date.     Agency.    Alias.    Message.

### PR DESCRIPTION
**Pull request by ThomasLuu00**
# Description

This PR adds the enhancement specified in issue#318. The columns hidden status and names may be changed in the settings when a user is logged in.  These settings will only appear when a user is logged in.  The styling for the table is misaligned when columns are hidden. Please let me know if you would like me to fix that as well in my PR.

Fixes #318

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated changelog.md with changes made

### CODE REVIEW

**Comment by davidmckenzie** [comment]
Oooh nice, will have to pull down and have a play. Dealing with the colspan attributes will be tough with this - it may need some fancy logic to determine those

**Comment by DanrwAU** [comment]
I've rebased this one to the 0.3.6 branch as we don't merge directly to master. 
I'll try and test this one tonight..

**Comment by DanrwAU** [comment]
This one is likely broken since the settings changes per user in 0.3.9. 

Will likely need to be redone for merge. @ThomasLuu00 still interested in this one?

**Comment by DanrwAU** [comment]
Abandonned - no commits in 3 years

**Pull request closed without merging**
