### PR TITLE
Footer URL Change

### PR DESCRIPTION
**Pull request by marshyonline**
# Description

Changes the link to the PagerMon repo in the footer to use a TinyCC URL.
The idea behind this is to stop protected instances showing in GitHub's Traffic Stats showing where people have visited the repo from.

Fixes # N/A

## Type of change

- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Following the Github link still works!

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have updated changelog.md with changes made

### CODE REVIEW

**Comment by davidmckenzie** [comment]
Not sure how much of an issue this is, it's only visible to contributors not to public. This does open up a potential (low probability, high impact) security vuln though - if your tinycc account was compromised then the URL could be redirected to bad code or a phishing site.

Am on the fence on this one :)

**Comment by DanrwAU** [comment]
Can we do something like this to prevent the referrer being sent?

https://stackoverflow.com/questions/5033300/stop-link-from-sending-referrer-to-destination

**Comment by marshyonline** [comment]
I like that idea
I will change it up

**Comment by marshyonline** [comment]
@davidmckenzie @DanrwAU Plz review

**Pull request merged**
