### PR TITLE
Hide MySQL Password in settings

### LINKED ISSUE #270: v0.3.0 Hide database password on settings page
**Describe the bug**
Databse password should be hidden on the settings page

**To Reproduce**
Use Mysql - See DB password isn't hidden

**Expected behavior**
DB Password is hidden.

Possibly needs a show button to confirm entry.

### PR DESCRIPTION
**Pull request by DanrwAU**
# Description

Add Button to hide/reveal MySQL Password in settings 

Fixes #270 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have updated changelog.md with changes made

### CODE REVIEW

**Comment by DanrwAU** [comment]
Added button, still need to figure out the JS to make it work

**Comment by DanrwAU** [comment]
Works Now 
image
image

**Comment by davidmckenzie** [comment]
If you wrap it in input group (forget the syntax) then it might be neater, will be on the same line with the button on the right then. Might need some css magic to look beautiful though

**Comment by DanrwAU** [comment]
i tried that, it kept making the line short and the button disappeared. I gave up lol...

**Comment by DanrwAU** [comment]
Hmph.... I hate when that happens
image

**Pull request merged**
