### PR TITLE
WIP: Rewriting a new reader.sh

### PR DESCRIPTION
**Pull request by eopo**
Complete rewrite of reader.sh
Workey workey, PR for visibility

# Description
This is a complete rewrite of the reader.sh.
It contains a uniform Message class as well as simplified and optimized code.
Also, function codes always get transmitted. The class could - in the future - put into it's own module so it can be imported server-side as well.

Related to #189 

## Type of change
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] To be tested

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated changelog.md with changes made

### CODE REVIEW

**Comment by marshyonline** [comment]
Hi, please submit this pagermon/pagermon_client

**Comment by DanrwAU** [comment]
This one needs to go to https://github.com/pagermon/pagermon-client, the client will be removed from this repo going forward

**Comment by marshyonline** [comment]
@DanrwAU at lest you gave a link 😂

**Comment by eopo** [comment]
Well, since it's a fork from the original one (here) I can only have the PR to here.
I'll reapply the changes to the client-repo tho and open a new PR as soon as the migration to the two repo's is completed.

**Pull request closed without merging**
