### PR TITLE
Add Sitename to Menu Header

### PR DESCRIPTION
**Pull request by s3m1s0n1c**
As per https://github.com/pagermon/pagermon/issues/320

Added Sitename to Menu bar
Added Field in settings to set sitename
Added variable in default.json
Added to sitename variable to route

### CODE REVIEW

**Comment by s3m1s0n1c** [comment]
@pagermon/collaborators 

Please review..  First time doing this stuff..

**Comment by s3m1s0n1c** [comment]
Mmm I wonder if I should link sitename also to the HTML title?

**Comment by marshyonline** [comment]
Yes, that should be the same 
Just to note, when you branch and submit PRs, do it from the next version branch and not master 
Other than that, fantastic job

**Comment by DanrwAU** [comment]
Yep i think so

**Comment by s3m1s0n1c** [comment]
> Mmm I wonder if I should link sitename also to the HTML title?

Change has been made to header.ejs

**Comment by s3m1s0n1c** [comment]
> Yes, that should be the same
> Just to note, when you branch and submit PRs, do it from the next version branch and not master
> Other than that, fantastic job

Sorry I'm still learning this git stuff and getting my head back into programing..

**Comment by davidmckenzie** [comment]
Actually... `title` variable should be kept separate and used for the html `title` tag, since it would need to be separate to the branding. "PagerMon - Login" looks right for the title, but not for the branding bit :)

**Comment by DanrwAU** [comment]
Done in #391 no messy merge commit yay

**Pull request closed without merging**
