### PR TITLE
Closes #340: New modal for messages

### LINKED ISSUE #340: Tapping a row on mobile view opens modal with more info
Since columns are limited on mobile view, add a modal popup that displays all columns for a particular message, respecting security restrictions. Either shows on tapping the message column (without breaking existing links for keyword filters), or add a small button to left of the time column

### PR DESCRIPTION
**Pull request by ThomasLuu00**
# Description
I added a modal for when a message is clicked that shows all the details for the message. It still requires some styling but the functionality is there.

Fixes #340 

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated changelog.md with changes made

### CODE REVIEW

**Comment by davidmckenzie** [comment]
Nice one, looks like this includes the changes from #339 as well though. Feel free to submit with only the modal changes, as I suspect we'll need to rework #339 a bit before it merges in due to the issues with colspan on the headers, and formatting issues

**Comment by DanrwAU** [comment]
Changed the base branch to v0.3.6 - we don't merge directly to master.

**Comment by marshyonline** [comment]
Other than the outlined issues - I really like the idea and am keen to see it implemented

**Comment by ThomasLuu00** [comment]
I have removed the old commits from #339 and changed the modal file name as requested.

**Comment by ThomasLuu00** [comment]
Okay, I think I messed up the rebase so it's not working, will try to fix it again.

**Comment by ThomasLuu00** [comment]
Fixed the problem, works now

**Comment by marshyonline** [comment]
Oh and please add your change to the CHANGELOG :)

**Comment by DanrwAU** [comment]
> It is not respecting "Hide Source"
It seems to be respecting "Hide Capcode" but is showing an empty field -
I feel Source and Capcode should be removed from the box if these options are enabled
@DanrwAU & @davidmckenzie Thoughts?

Agreed needs to hide these fields if they aren't applicable. Also needs some prettiness, that's not my wheelhouse tho

**Comment by ThomasLuu00** [comment]
If someone has an idea of how it should look, I will add the style changes. But yes, I will add some changes to respect the hidden columns settings.

**Comment by ThomasLuu00** [comment]
I have updated the changelog and implemented the hidesource and hidecapcode changes.
Screen Shot 2019-11-20 at 6 39 55 PM

**Comment by s3m1s0n1c** [comment]
Is there an option to turn it off as I probably wouldn't want this on my site..

Sorry to be annoying..

Thanks
Sonic

**Comment by davidmckenzie** [comment]
@s3m1s0n1c it should only display on mobile view when columns are truncated, where it would be useful. May consider moving it to an unobtrusive button pinned to the right instead of from clicking the row

I'll take a look at prettifying this after the oracle saga is over :)

**Comment by marshyonline** [comment]
If this is for mobile only - I was seeing the Modal on a desktop

**Comment by eopo** [comment]
How about accordion view. We could even enable them on desktop to view maps or other stored plugin data 🤔

**Comment by marshyonline** [comment]
+1 for @eopo's idea

**Comment by davidmckenzie** [comment]
oooh accordian is nice, good idea, kinda like what I started on with #167 / #171 but never got around to finishing

**Comment by ThomasLuu00** [comment]
I added the change to make the modal so it only appears for mobile but not small browsers.  But based on the discussion here, seems like an accordian view is more popular. I can work on that view as well, should I open up a new issue?

**Comment by DanrwAU** [comment]
Is this one cancelled in favour of #348 ?

**Comment by DanrwAU** [comment]
Abandonned - no commits in 3 years

**Pull request closed without merging**
