### PR TITLE
Improved wildcard feature

### PR DESCRIPTION
**Pull request by eopo**
If a match between message and alias was due to a wildcard,
a new row "wildcard" is returned. In the message popover,
the user is now asked if he wants to create a new alias using the message,
if the match was using a wildcard.

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [X] Own testing system
- [X] Own production system
- [ ] Request testing on another system!!!

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated changelog.md with changes made

### CODE REVIEW

**Comment by davidmckenzie** [comment]
Oh that's neat logic, I like it

**Comment by DanrwAU** [comment]
Oooo I've tried to fix this a few times and could never solve this... Nice work

**Comment by davidmckenzie** [comment]
No idea whether that will work with other DB types... if it does fail you could just include capcodes.address and include the logic in UI (`if capcodes.address index of % or * or whatever`)

**Comment by eopo** [comment]
Fixed two bugs I had, does work on both of my systems (develop state with this change and master state with heavy customizations) now. I'd like to have one of you try it as well ;)

**Comment by eopo** [comment]
> No idea whether that will work with other DB types... if it does fail you could just include capcodes.address and include the logic in UI (`if capcodes.address index of % or * or whatever`)

I checked the syntax of CASE, should be the same for SQLITE and OracleDB according to their docs. Would be nice if someone running sqlite and someone running oracle could double check that tho.

**Comment by DanrwAU** [comment]
>  someone running oracle could double check that tho.

Wait, there is someone crazy enough to run Orcale? 

I'll upgrade my dev box later and see how it goes on MySQL and SQLite :)

**Comment by davidmckenzie** [comment]
> > someone running oracle could double check that tho.
> 
> Wait, there is someone crazy enough to run Orcale?
> 
> I'll upgrade my dev box later and see how it goes on MySQL and SQLite :)

Just me on my dev box that I never cut over :joy: I likely won't get around to testing this on there so feel free to merge if MySQL and SQLite work

**Comment by eopo** [comment]
Hmm. I'm thinking it might actually be better to store the wildcard match field permanently with the message, to improve the alias rematching process. It could then just re-parse all messages with wildcard fielt set true or that are linked to an alias that was changed.
New table that stores alias id of aliases that have been changed. Every time the alias match is re-run it rematches all messages with wildcard field and all messages, whose alias id is contained in the changed aliases table.

**Comment by DanrwAU** [comment]
This seems to be working ok for me. 

Only issue i have is the UI is kinda ugly 🤣 

image

**Comment by DanrwAU** [comment]
Much betterer
image

**Review by DanrwAU — APPROVED** [review]
Test on SQLite and MySQL, seems to work correctly. 

I'm happy to merge this one to be included in 0.3.11

**Comment by eopo** [comment]
🎉

**Pull request merged**
