### PR TITLE
WIP: Multi User Support with sign up 

### PR DESCRIPTION
**Pull request by nicko170**
# Description

Multi user support with signup allowed

DEMO: https://pagermon-dev.devlan.io/

Fixes # (issue)

## Type of change
Feature Addition

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Still being tested - WIP

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated changelog.md with changes made

### CODE REVIEW

**Comment by 112bzo** [comment]
it works, but a user can chance the alias?

**Comment by DanrwAU** [comment]
> it works, but a user can chance the alias?

This is still super dooper work in progress, nowhere near finished as yet. Not ready for testing or deployment.

**Comment by DanrwAU** [comment]
As a next step for this one i'd like to add 2FA as well using something like this 😉 

https://github.com/yeojz/otplib

**Comment by DanrwAU** [comment]
Closing Abandonned

**Pull request closed without merging**
