### PR TITLE
New Prowl plugin - Similar to Pushover.

### PR DESCRIPTION
**Pull request by eopo**
# Description

Adds a Plugin for "Prowl" - Really similar to Pushover, just only for iOS. Looks ugly af, but works better on Apple Watch.
I should admit that the plugin itself is just a modified copy of the pushover one.

New dependency: 'node-prowl' at latest

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Production use for a few weeks.

Steps for reproduction:
Get Prowl, get your userkey, enable the plugin, input your key and an application name (required by Prowl, can be anything), go to some alias you want pushing enabled for, enter your user key (Or multiple ones comma separated) and maybe the other settings and wait for messages (or generate your own ones.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have updated changelog.md with changes made

### CODE REVIEW

**Comment by eopo** [comment]
Did not update changelog (Since it's not a real update and it's your decision when this is gonna be merged).
Did not write a single comment but it's really similar to the pushover plugin and really really self-explaining.

**Comment by marshyonline** [comment]
Also please update the README.MD with the new plugin info :tada:

**Comment by marshyonline** [comment]
I've fixed the merge branch - we no longer merge to master.
My apologies, I didn't notice to now. 

One merge conflict to sort and she's good by me :)

**Comment by marshyonline** [comment]
I'm happy to sort the conflict in the next hour if you leave it :)

**Comment by eopo** [comment]
Already solved

**Comment by s3m1s0n1c** [comment]
Some Documentation would be nice for the Wiki.. :)

**Pull request merged**
