### PR TITLE
Fix High Resolution Display Properly

### PR DESCRIPTION
**Pull request by DanrwAU**
# Description

Fixes Mobile properly - leading on from #241 and fixing properly

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Tested Display on Galaxy S10 which was not affected by changes in #241 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have updated changelog.md with changes made

### CODE REVIEW

**Comment by DanrwAU** [comment]
@pagermon/collaborators This continues on from #241 and seems to properly fix it  on my devices 👍

**Comment by davidmckenzie** [comment]
Hmm, this might break resized windows, like if you had a browser window open on desktop but only half screen width. Might need to duplicate that so it runs on both max-device-width and max-width.

Dunno how easy it is to get on the s10, but are you able to find what it's reporting for the device-width and the actual viewport width?

**Comment by DanrwAU** [comment]
Device width is 412px max width is 1440px. 

Would setting the device orientation to filter only devices in portrait help or should we add NoTiny
Back in as well?

**Comment by davidmckenzie** [comment]
I think it's more that max-width *should* be doing what you need, if I understand it correctly. Since max-width is the width of the current browser window, and max-device-width is the max width reported by the device itself (like the screens actual resolution), in theory max-width would always be the more accurate number. Unless something funky happening with upscaling that makes it not do stuff right.

Upscaling fuckery is the only reason I can think of that max-width would be higher than max-device-width

**Comment by DanrwAU** [comment]
@davidmckenzie The last 2 commits introduce a noSmall class with the old parameters which fixes resizing 😄

**Pull request merged**
