### PR TITLE
Gotify Plugin pagermon/pagermon#257

### LINKED ISSUE #257: Gotify Plugin
Gotify is a self-hosted push notification service, think of it like PushBullet you have control over.

The Github repo:
https://github.com/gotify

Info on making a plugin with Gotify:
https://gotify.net/docs/plugin
https://gotify.net/docs/plugin-write

### PR DESCRIPTION
**Pull request by ryaneast**
# Description

Adds plugin for Gotify

Fixes #257 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Testing using wildcard alias and working prefectly

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have updated changelog.md with changes made

### CODE REVIEW

**Comment by ryaneast** [comment]
All tested and working

**Comment by davidmckenzie** [comment]
Looks good! I note that it only uses http - from a quick google, Gotify supports SSL. Might be worth adding settings switch to send via https

**Comment by dh47** [comment]
Working and tested from me too.

**Comment by ryaneast** [comment]
I've added SSL support
I left rejectUnauthorized false to allow self signed cetificates

**Comment by DanrwAU** [comment]
Chnaging the base for this to v0.3.0 - we don't merge directly to master anymore 😁

**Comment by DanrwAU** [comment]
I don't have a gotify server setup, i'll try and get one spun up at some stage this week to test as well if nobody else does 😁

**Comment by ryaneast** [comment]
A Docker one you can spin up in like 5mins

**Comment by dh47** [comment]
> 
> 
> I don't have a gotify server setup, i'll try and get one spun up at some stage this week to test as well if nobody else does 😁

**Comment by ryaneast** [comment]
Yeah both should work fine I think.
I'll try it out and see.
I was just being lazy when I wrote it I think :)

**Comment by ryaneast** [comment]
Changed it to add the `options.rejectUnauthorized = false` inside the SSL if

**Comment by davidmckenzie** [comment]
Nice one, merging :)

**Pull request merged**
