### PR TITLE
Add Sticky Buttons

### LINKED ISSUE #195: Save buttons (settings, alias, etc) should stick to screen
Scrolling the whole page to hit save sucks

### PR DESCRIPTION
**Pull request by DanrwAU**
# Description

Add's sticky buttons to all pages with buttons. 
Standardizes placement across all pages. 

Opinions @pagermon/collaborators ?

Fixes #195 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Tested functionality of all buttons. 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have updated changelog.md with changes made

#Screenshots

image
image
image
button

### CODE REVIEW

**Comment by davidmckenzie** [comment]
Oooh pretty. How does it look on mobile?

**Comment by DanrwAU** [comment]
Had me worried for a second there. 

Looks pretty good i think, i'll post some pictures later this morning

**Comment by DanrwAU** [comment]
Settings and Alias screens look fine.

AliasDetail is a bit of a concern.... 

image
image
image

**Comment by davidmckenzie** [comment]
Hmm for mobile it might be better to have it as a floating sticky footer that spans horizontally. Will have a think on this one

**Comment by DanrwAU** [comment]
Your idea is probably better but turning off the global buttons makes it a little nicer. 

image

**Comment by DanrwAU** [comment]
I couldn't figure out how to do it @davidmckenzie lol. 

Happy for anyone else to have a go 😉

**Comment by DanrwAU** [comment]
I made the buttons a bit smaller on mobile, i think it works not too bad now 😁 

image

**Pull request merged**
