### PR TITLE
Fixes Layout of Buttons on mobile devices

### PR DESCRIPTION
**Pull request by geelongmicrosoldering**
Fixes Layout of buttons (like on admin page) for mobile devices

# Description
Not a heap to say on this. Just some CSS overrides to fix the layout of buttons on mobile devices. Needs to be tested and confirmed
**Desktop View Admin page (no change):**
pm_settings_before_desk

**Mobile View Admin page (before css override):**
pm_settings_before_mob

**Mobile View Settings page (before css override):**
pm_settings2_before_mob

**Mobile View Admin page (after css override):**
pm_settings_after_mob

**Mobile View Settings page (after css override):**
pm_settings2_after_mob

Fixes # (Layout of buttons on mobile devices)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- [x] Tested on own server

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

**Comment by geelongmicrosoldering** [comment]
Note to self: Don't rename branch after opening pull request. Whoops

**Review by eopo — DISMISSED** [review]
Just an additional media query in css, looks fine to me.

**Comment by DanrwAU** [comment]
Needs a changelog entry.

**Review by DanrwAU — APPROVED** [review]
Looks Good

**Pull request merged**
