### PR TITLE
Fix Error [ERR_HTTP_HEADERS_SENT]

### PR DESCRIPTION
**Pull request by nic-hanna**
# Description

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

Combine res.status(200) and res.send(message) to res.status(200).send(message)

# Type of Issue

Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Tested on local machine

# Checklist:

- [x] I have updated changelog.md with changes made

### CODE REVIEW

**Comment by geelongmicrosoldering** [comment]
Ooh interesting. I dont have time to look into this right now but i feel like this is somehow related to #500

**Comment by nic-hanna** [comment]
> Ooh interesting. I dont have time to look into this right now but i feel like this is somehow related to #500

I don't believe the issues would be related, this fix is only due to the usage of res.status in this code base as been deprecated and produces a warning not error.

**Comment by geelongmicrosoldering** [comment]
See line 207 of app.js

I think you inadvertently solved an issue you werent looking for in a different file. I never notice the res.render was preceded by res.status

**Comment by nic-hanna** [comment]
Might be worth going through all the routes and checking all the res.status.

**Comment by geelongmicrosoldering** [comment]
Yeah i think so. It seems replacing 207/208 with
```res.status(err.status || 500).render(path.join(__dirname,'themes',theme, 'views', 'global', 'error'), { title: title });```

Would solve that issue. I never returned to it and seeing this PR jogged my memory.

**Comment by DanrwAU** [comment]
Changed base repo to develop. We don't merge directly to master

**Review by DanrwAU — DISMISSED** [review]
Looks good, matches express doco 
https://www.geeksforgeeks.org/express-js-res-status-function/?ref=ml_lbp

**Review by DanrwAU — APPROVED** [review]

**Pull request merged**
