### PR TITLE
Add Dark Theme Card View

### PR DESCRIPTION
**Pull request by Maaaaattee**
# Description

Addition of Dark Theme Card View. Obviously it won't be everyone's cup of tea (@DanrwAU cough) ;) but who said we can only have one right!

## Type of change

Please delete options that are not relevant.

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Locally Tested

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have updated changelog.md with changes made

### CODE REVIEW

**Comment by Maaaaattee** [comment]
Crap... missed something... one moment..

**Comment by Maaaaattee** [comment]
Try that again... ready to go now

**Comment by DanrwAU** [comment]
Is this the intended colourscheme? 

image

**Comment by DanrwAU** [comment]
The simple webhook plugin has a huge gap on the setting screen? 

image

**Comment by DanrwAU** [comment]
The settings page has a search box in the footer, this is a regression i think i fixed this in 0.3.7 on default theme 

image

**Comment by DanrwAU** [comment]
Text is wrong colour on the reset password screen
image

**Comment by DanrwAU** [comment]
Dropdowns have white text on white background

**Comment by DanrwAU** [comment]
Iconsize defaults to blank, then once something is selected the blank option disappears 

image

**Comment by Maaaaattee** [comment]
> Is this the intended colourscheme?
> 
> image

Is that to do with your new import function?

**Comment by DanrwAU** [comment]
> The settings page has a search box in the footer, this is a regression i think i fixed this in 0.3.7 on default theme
> 
> image

Never mind this isn't fixed in master 🤣

**Comment by DanrwAU** [comment]
@pagermon/collaborators I'm going to merge this one to a local branch and go about fixing the little bits and peices that aren't working (hopefully 🤣 ) if nobody has an objections 😁

**Comment by marshyonline** [comment]
Sounds good

**Review by marshyonline — APPROVED** [review]

**Comment by s3m1s0n1c** [comment]
I object!!!!

This is a great idea 👍

**Pull request merged**
