### PR TITLE
WIP - Muchwowverytheme - Initial upload of dark theme changes

### LINKED ISSUE #381: Alternative UI themes
**Is your feature request related to a problem? Please describe.**
A possible future UI theme feature that was discussed on Discord.

**Describe the solution you'd like**
Look at alternative themes for the main UI. Dark/Light etc..

**Describe alternatives you've considered**
Possibly look at integrating Bootstrap 4 into the new themes?

### PR DESCRIPTION
**Pull request by Maaaaattee**
# Description

### The sexxy dark theme addition.
Adding new UI changes to the front end of Pagermon. Gives a new alternative view "Card" style instead of using the normal table grid view.
Toggle it on and off in the admin global settings

Fixes #381 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Tested on both mobile and desktop. New dark theme works well on mobile.
- [x] Checkbox in admin settings turns it on and of as expected

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated changelog.md with changes made

### CODE REVIEW

**Comment by DanrwAU** [comment]
Set to WIP we'll need to come up with a framework for themes i think

**Comment by Maaaaattee** [comment]
Yea, would probably be a good idea.. I've left it in as clean of a state as possible and have split it all up so you can turn on and off etc..

**Comment by s3m1s0n1c** [comment]
Looks good so far.. 

A few comments.

- Font is small.. Maybe u can adjust to take up most of the height of the row

- Icons are small.. Make them a bit bigger.

- Transform while page into same colour scheme - Top Bar and Page Change Bar

That's my 5 cents for now :)

**Comment by DanrwAU** [comment]
Merging this into the "muchwowverytheme" branch on pagermon repo

**Pull request merged**
